PROC SQL;
CREATE TABLE FMP_ORI
AS SELECT 
*,
'FMP' AS FMP
FROM FMP
;
PROC SQL;
CREATE TABLE K_PRO_ORI
AS SELECT 
*,
'K_PRO' AS K_PRO
FROM K_PRO
;
PROC SQL;
CREATE TABLE NIGIRI_ORI
AS SELECT 
*,
'NIGIRI_MOJO' AS NIGIRI_MOJO
FROM NIGIRI_MOJO
;
PROC SQL;
CREATE TABLE NZK_ORI
AS SELECT 
*,
'NZK' AS NZK
FROM NZK
;


PROC SQL;
CREATE TABLE FOCUS_KEY
AS SELECT NIGIRI_ORI.HIGHEST_PRODUCER_CD AS HIGHEST_PRODUCER_CD3, FMP_ORI.HIGHEST_PRODUCER_CD AS HIGHEST_PRODUCER_CD2, NZK_ORI.HIGHEST_PRODUCER_CD AS HIGHEST_PRODUCER_CD1,
NIGIRI_ORI.NIGIRI_MOJO AS NIGIRI_FLG, FMP_ORI.FMP AS FMP_FLG, NZK_ORI.NZK AS NZK_FLG
FROM FMP_ORI FULL OUTER JOIN NZK_ORI
ON FMP_ORI.HIGHEST_PRODUCER_CD=NZK_ORI.HIGHEST_PRODUCER_CD
FULL OUTER JOIN NIGIRI_ORI
ON FMP_ORI.HIGHEST_PRODUCER_CD=NIGIRI_ORI.HIGHEST_PRODUCER_CD;
PROC SQL;
CREATE TABLE FOCUS_TABLE
AS SELECT
(CASE
WHEN HIGHEST_PRODUCER_CD2 IS NULL THEN HIGHEST_PRODUCER_CD1
WHEN HIGHEST_PRODUCER_CD1 IS NULL THEN HIGHEST_PRODUCER_CD3
ELSE HIGHEST_PRODUCER_CD2 END) AS HIGHEST_PRODUCER_CD,
(CASE WHEN NZK_FLG IS NULL THEN '' ELSE 'NZK' END) AS NZK_FLG,
(CASE WHEN FMP_FLG IS NULL THEN '@' ELSE '@FMP' END) AS FMP_FLG,
(CASE WHEN NIGIRI_FLG IS NULL THEN '@' ELSE '@NIGIRI' END) AS NIGIRI_FLG
FROM FOCUS_KEY;
QUIT;
PROC SQL;
CREATE TABLE KANSAI_FOCUS_FLG
AS SELECT
HIGHEST_PRODUCER_CD,
FMP_FLG,
NZK_FLG,
NIGIRI_FLG,
COMPRESS(NZK_FLG||FMP_FLG||NIGIRI_FLG) AS KANSAI_FLAG
FROM FOCUS_TABLE;
PROC SQL;
CREATE TABLE PRO_FOCUS
AS SELECT A.*,
(CASE WHEN B.KANSAI_FLAG IS NULL THEN '@@' ELSE B.KANSAI_FLAG END) AS KANSAI_FLAG
FROM JENN.JEN_HON_PRO2 A LEFT JOIN KANSAI_FOCUS_FLG B
ON A.HIGHEST_PRODUCER_CD=B.HIGHEST_PRODUCER_CD;

PROC SQL;
CREATE TABLE PRO_FOCUS_1
AS SELECT
A.*,
(CASE WHEN B.K_PRO IS NULL THEN '@' ELSE '@K_PRO' END) AS K_PRO
FROM PRO_FOCUS A LEFT JOIN K_PRO_ORI B
ON A.OLD_PRODUCER_CD=B.PRODUCER_CD
;

PROC SQL;
CREATE TABLE KANSAI_FOCUS_FLG_1
AS SELECT
*,
COMPRESS(KANSAI_FLAG||K_PRO) AS KANSAI_FLAG1
FROM 
PRO_FOCUS_1
;
DATA PRO_FOCUS_FLG_2;
SET KANSAI_FOCUS_FLG_1 (DROP=KANSAI_FLAG K_PRO);
/*IF KANSAI_FLAG1='@' THEN DO; KANSAI_FLAG1='@@@@';END;*/
/*IF KANSAI_FLAG1='@K_PRO' THEN DO; KANSAI_FLAG1='@@@K_PRO';END;*/
RENAME KANSAI_FLAG1=KANSAI_FOCUS;
RUN;
proc export data=PRO_FOCUS_FLG_2 OUTFILE="\\rkda0050\SME_team\Z_Working_files\Jenny\PRO_FOCUS_FLG.csv" DBMS=csv REPLACE; RUN;
